### test
GET http://localhost:8080/up
###
GET http://localhost:8080/subject
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOnsiU3R1ZGVudCI6MX0sImV4cCI6MTY0MDMyNTIzNX0.Zc27vrvhOxE5FBGy8IH3IaFKvJ0dNpdu-wxDbQDi1Xk

###
GET http://localhost:8080/subject
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOnsiU3R1ZGVudCI6MX0sImV4cCI6MTY1ODkwODk2MH0.NhP_Livsc738E7O2d2Tv9y-WEcxal5klfrH0UKjEnPw

### one sub
GET http://localhost:8080/subject/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOnsiU3R1ZGVudCI6MX0sImV4cCI6MTY0MDMyNTIzNX0.Zc27vrvhOxE5FBGy8IH3IaFKvJ0dNpdu-wxDbQDi1Xk

###
POST http://localhost:8080/subject
Content-Type: application/json

[{
    "coursecode": "18CS56",
    "name": "small junior",
    "semester": 7,
    "isglobal": true,
    "deptid": "CSE",
    "maxcapacity": 340
}]
### list users
GET http://localhost:8080/user

### add user (list)
POST http://localhost:8080/user
Content-Type: application/json

[{
    "name":"Atreya",
    "email":"atreya@gmail.com",
    "pwd":"hello",
    "semester":7,
    "deptid":"CSE"
},
{
    "name":"Atreya Bain",
    "email":"atreyabain@gmail.com",
    "pwd":"hello",
    "semester":5,
    "deptid":"CSE"
}
]

### add user (one)
POST http://localhost:8080/user
Content-Type: application/json

{
    "name":"Atreya",
    "email":"atreya@gmail.com",
    "pwd":"hello",
    "semester":7,
    "deptid":"CSE"
}

### login
POST http://localhost:8080/auth
Content-Type: application/json

{
    "email":"atreya@gmail.com",
    "pwd":"hello"
}

###
GET http://localhost:8080/dept