### test
GET http://localhost:8080/up
###
GET http://localhost:8080/subject
###
GET http://localhost:8080/subject/1
###
POST http://localhost:8080/subject
Content-Type: application/json

{
    "id":1,
    "name":23,
    "courseCode":"pain"
}

### list users
GET http://localhost:8080/user

### add user
POST http://localhost:8080/user
Content-Type: application/json

{
    "name":"Atreya",
    "email":"atreya@gmail.com",
    "pwd":"hello",
    "semester":7,
    "deptid":"CSE"
}

### login
POST http://localhost:8080/auth
Content-Type: application/json

{
    "email":"atreya@gmail.com",
    "pwd":"hello"
}

###
GET http://localhost:8080/dept