### test
GET http://localhost:8080/up
### Get all subs
GET http://localhost:8080/subject/all


### Get subjects for user
GET http://localhost:8080/subject
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOnsiU3R1ZGVudCI6MX0sImV4cCI6MTY1OTI1MzI1OH0.4-sbULLyBjHl7W6rd7Qd9hdZPcktlOVf3mVwvirhRd4

### one sub
GET http://localhost:8080/subject/18ME51
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOnsiU3R1ZGVudCI6Mn0sImV4cCI6MTY1ODkzMjQ2NX0.hEUtbBdS07mq5NGQSLh_GxDY_DtLyRcH1jGM0UlpJoA

### Add subjects
POST http://localhost:8080/subject
Content-Type: application/json

[{
    "coursecode": "18ME51",
    "name": "Global Course From Mech",
    "semester": 7,
    "isglobal": true,
    "deptid": "ME",
    "maxcapacity": 340
},{
    "coursecode": "18CS52",
    "name": "Non Global Course from cse",
    "semester": 7,
    "isglobal": false,
    "deptid": "CSE",
    "maxcapacity": 340
},
{
    "coursecode": "18ME52",
    "name": "Non Global Course from ME",
    "semester": 7,
    "isglobal": false,
    "deptid": "ME",
    "maxcapacity": 340
}
]
### list users
GET http://localhost:8080/user

### add user (list)
POST http://localhost:8080/user
Content-Type: application/json

[{
    "name":"Atreya",
    "email":"atreya@gmail.com",
    "pwd":"hello",
    "semester":7,
    "deptid":"CSE"
},
{
    "name":"Atreya Bain",
    "email":"atreyabain@gmail.com",
    "pwd":"hello",
    "semester":5,
    "deptid":"CSE"
}
]

### add user (one)
POST http://localhost:8080/user
Content-Type: application/json

{
    "name":"Atreya",
    "email":"atreya@gmail.com",
    "pwd":"hello",
    "semester":7,
    "deptid":"CSE"
}

### login
POST http://localhost:8080/auth
Content-Type: application/json

{
    "email":"atreya@gmail.com",
    "pwd":"hello"
}

### Get departments
GET http://localhost:8080/dept


### Get booking
GET http://localhost:8080/book
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOnsiU3R1ZGVudCI6MX0sImV4cCI6MTY1OTMzOTcwM30.3rwMiijBh9zFZiqSREpFnaCACm32-tO8wXgiGKbRuPI

### Make booking for student
POST http://localhost:8080/book
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOnsiU3R1ZGVudCI6MX0sImV4cCI6MTY1OTMzOTcwM30.3rwMiijBh9zFZiqSREpFnaCACm32-tO8wXgiGKbRuPI

{
    "course_code":"18CS52"
}
