[package]
name = "elebuild"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.12"
argonautica = { version = "0.2.0", features = ["serde"] }
dotenv = "0.15.0"
futures = "0.3.21"
jsonwebtoken = "8.1.1"
log = "0.4.17"
pretty_env_logger = "0.4.0"
serde = "1.0.133"
serde_json = "1.0.74"
sqlx = { version = "0.6.0", features = ["runtime-actix-native-tls","postgres","uuid"] }
uuid = "1.1.2"

[features]

[profile.release]
lto = true
