[package]
name = "elebuild"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.12"
argonautica = { version = "0.2.0", features = ["serde"] }
dotenv = "0.15.0"
jsonwebtoken = "7.2.0"
serde = "1.0.130"
serde_json = "1.0.72"
sqlx = { version = "0.5.9", features = ["runtime-actix-native-tls","postgres","uuid"] }
uuid = "0.8.2"

[features]

[profile.release]
lto = true
