version: "3"
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./etc:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata: